# model list and their costs 
gemini-2.0-flash : 
  input_cost : 0.10
  output_cost :  0.40

gemini-2.5-flash :
  input_cost : 0.30
  output_cost :  2.50

gemini-2.5-pro : 
  input_cost : 1.25
  output_cost :  10.0

gpt-4.1-2025-04-14 :
  input_cost : 2
  output_cost :  8

gpt-4.1-mini-2025-04-14 :
  input_cost : 0.40
  output_cost :  1.60

gpt-4o-2024-08-06 : 
  input_cost : 2.5
  output_cost :  10.0

gpt-4o-mini-2024-07-18 : 
  input_cost : 0.15
  output_cost :  0.60